### ISSUE TITLE
How to use wireshark to parse packet of websocket？

### ISSUE THREAD

**Issue by killerdbob** [yoursunny/NDNts#11]
Hi，
     I would like to ask if there is a way to parse ndnts packet by using wireshark? I found that it is possible to analyse udp and tcp packets, but websocket only shows small fragments.

**Comment by yoursunny** [comment]
WebSocket and WebTransport are encrypted traffic.
It isn't possible to see the payload in Wireshark.

You can use the **FwTracer** type from `@ndn/fw` package to see packet names on the console.
If you need more information from the packets, look at how `FwTracer` is implemented, and implement your own logic with these hooks.

**Comment by killerdbob** [comment]
ok thankyou
