### ISSUE TITLE
Connect to local router over wss

### ISSUE THREAD

**Issue by radara09** [yoursunny/NDNts#15]
I tried to recreate the website from your website (https://yoursunny.com/t/2020/NDNts-webpack-start/) and successfully connected to the NDN Testbed. But, we want to connect the website to our local testbed, is there any source or recommendation to do this?
Thank you

**Comment by yoursunny** [comment]
You can use `@ndn/ws-transport` package to directly connect to a specific router:

```ts
import { WsTransport } from "@ndn/ws-transport";

await WsTransport.createFace({}, "wss://router.example.org/");
```

**Comment by radara09** [comment]
thank you now it's connected
