### ISSUE TITLE
connecting website to vm server on microsoft azure 

### ISSUE THREAD

**Issue by radara09** [yoursunny/NDNts#17]
so we are deploying a website based on https://yoursunny.com/t/2020/NDNts-webpack-start/ and have deployed to netlify, 
and have customized it to use websocket using ```await WsTransport.createFace({}, "wss://router.example.org/"); ``` 
and using multiple options for ```"wss://"``` such as "wss://ourlink.com/" "wss://ourlink.com:9696/" wss://ourlink.com:9696/ws/
each issuing the following error 
https://postimg.cc/gallery/c0Sgptx

we created the server side in the azure cloud vm by allowing all inbound and outbound to enter and exit in the VM, nfd has been run on the server and there is not a single log in. 

is there any source or recommendation in solving this
Thank you.

**Comment by yoursunny** [comment]
Please paste any error messages in textual format, not as pictures.
Please [attach files](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files) to this issue, not linking to pageful of ads.

**Comment by radara09** [comment]
my apologies 
these are the error messages
`►WebSocket connection to 'wss://ndn-ehealth.australiaeast.cloudapp.azure.com:9696/ws/' failed: WebSocket is closed before the connection is established. ws-transport_browser.js:82`

and 

`► WebSocket connection to 'wss://ndn-ehealth.australiaeast.cloudapp.azure.com/ failed:
ws_browser.js:2 
`

**Comment by yoursunny** [comment]
> wss://ndn-ehealth.australiaeast.cloudapp.azure.com:9696/ws/

The server is not listening for TLS connections on port 9696.
It is responding for insecure HTTP requests only, but that is not supported by NDNts.

> wss://ndn-ehealth.australiaeast.cloudapp.azure.com/

The server is not listening on port 443, so you get connection refused.
You'll need to fix your server.

Easiest way is using the YaNFD forwarder that natively supports accepting TLS-encrypted WebSocket connections.
See https://github.com/named-data/YaNFD/pull/12#issue-1013978070 *Test instructions for "wss" scheme* for how to configure.

**Comment by radara09** [comment]
thank you it's solved now both the server and client are online
