### ISSUE TITLE
failed to send json file to server

### ISSUE THREAD

**Issue by mrifqibhagas** [yoursunny/NDNts#19]
i tried to recreate from your tutorial (https://yoursunny.com/t/2020/NDNts-webpack-start/)
when i tried to send interest and parameters from my website to router -> server it works. But when i wanna try to send interest and bunch of parameters and converted into json, an error popped up

"Uncaught runtime errors :
ERROR
obj is not Encodable ....."

my website still able to connect to router but i cant send the json, here is my code
`const dataEncoded = encoder.encode(name, age, sex, disease);
const jsonData = JSON.stringinfy(dataEncoded);
interest.appParameters = jsonData;`

and i wanna ask another question too
If I have a form in html then I take its **value** so that it can be received on the server side, should i convert that **value** into ndn element first? and can the server accept json format or not

Thanks!

**Comment by yoursunny** [comment]
> `const jsonData = JSON.stringinfy(dataEncoded);`
> `interest.appParameters = jsonData;`

This will not work.
`jsonData` has type `string`, but `interest.appParameters` shall be `Uint8Array` type.

If you are writing JavaScript instead of TypeScript, you should still use the TypeScript compiler to perform type checking, which helps you catch such errors.

**Comment by mrifqibhagas** [comment]
Thanks for the help sir! now it's working
