### ISSUE TITLE
TypeError: input.split is not a function or its return value is not iterable

### ISSUE THREAD

**Issue by ernoaapa** [yoursunny/NDNts#2]
Thanks for awesome NDN libraries!

Followed example in the [`cat` README](https://github.com/yoursunny/NDNts/blob/master/packages/cat/README.md#example) and got following error

```bash
ndncat put-segmented /A </tmp/1.bin

ndncat put-segmented <name>

publish segmented object

Positionals:
  name  name prefix                                          [string] [required]

Options:
  --help         Show help                                             [boolean]
  --version      Show version number                                   [boolean]
  --convention1  use 2014 Naming Convention           [boolean] [default: false]
  --rdr          publish RDR metadata packet           [boolean] [default: true]
  --ver          version number; 'none' to omit version component, 'now' to use
                 current timestamp                     [string] [default: "now"]
  --file         read from file instead of stdin                        [string]
  --chunk-size   segment payload size                   [number] [default: 4096]

TypeError: input.split is not a function or its return value is not iterable
    ...
```

Looks like that the [`instanceof Component`](https://github.com/yoursunny/NDNts/blob/2a9b21d7e107a12d3bcbb4ae299f787b5c974034/packages/packet/src/component.ts#L52-L54) check fails every time even though `input` is instance of `Component` class.

**Comment by ernoaapa** [comment]
Found the issue. I was fetching some dependencies from https://ndnts-nightly.netlify.app and some from https://ndnts-nightly.ndn.today. Which one is btw. the official one?

**Comment by yoursunny** [comment]
Nightly packages should be installed from `https://ndnts-nightly.ndn.today/` domain.
It used to be on Netlify but their ToS says I'm not supposed to host binaries.
