### ISSUE TITLE
add PrefixAnnouncementHeader

### ISSUE THREAD

**Issue by Pabears** [yoursunny/NDNts#24]
Hi bro, one of your great works is SelfLearningStrategy, could you please Implement the PrefixAnnouncement in LPPacket? I want to improve your SelfLearningStrategy. Add a PA process to the SelfLearningStrategy::AfterReceiveInterest() for implementing Kite, so the Mobility Producer could send Interest to the Immobile Consumer (or RV) to set the Trace in FIB.

**Comment by Pabears** [comment]
and I will remove some limitations in your [LPPacket Spec](https://redmine.named-data.net/projects/nfd/wiki/NDNLPv2)  , like "This field can only appear on a Data. If this field appears on an Interest or a Nack, the LpPacket MUST be dropped. If the self-learning forwarding protocol support feature is disabled or the chosen forwarding strategy does not support self-learning, this field SHOULD be ignored."

**Comment by yoursunny** [comment]
**PrefixAnnouncement** field is typically used between forwarders.
NDNts is a library for end hosts.
What's the use case of this field on the end hosts?

**Comment by Pabears** [comment]
I have developed several cloud microservices based on NDNts. These services run in Kubernetes (k8s) pods, but there is no NFD (Named Data Networking Forwarding Daemon) within these pods. Instead, I deployed numerous NFDs on cloud VMs hierarchically, ranging from the edge to the central cloud. Additionally, I developed numerous client applications with NDNts that run on mobile devices. The network topology is structured as follows:

client1 -> edge NFD1 --\-> cloud NFD1  --\ <--- service3
 _                                       / \                              \                    /--- service2
client1' -> edge NFD2 /---> cloud NFD2 ---> root NFD <--- service1


Edge NFDs connect to all cloud NFDs, and all cloud NFDs connect to the root NFD.
Services could connect to which NFD depends on applications, eg. latency-sensitive applications should deploy on edge.
The client connects to edge NFD1 first and then it moves to edge NFD2.

In this case, if the client as a producer, It should register his routable prefix from the edge NFD that it is connecting to the root NFD, so any service as a consumer could send Interest to the client.

I intend to register the client's routable prefix using Kite. Upon delving into Kite's mechanics, I discovered that by adding a PrefixAnnouncement to the Link-Layer Protocol (LLP) Packet of an Interest, the client can register the prefix across all NFDs from the client to the producer of the Interest. This process requires only the definition of a ReverseSelfLearningStrategy and the execution of the Prefix Announcement (PA) process within the Strategy::afterReceiveInterest() method.

**Comment by Pabears** [comment]
And I just find that if I define a specifical Interest convension It will work too. I could define a Interest with Name:
/kite/trece(untrace)/<the prefix to be traced>/signature
ForwardingHint: the routable prefix of root NFD

strategyChoose: /kite -> KiteStrategy, this strategy will set the fib afterReceiveInterest and forwarding the Interest to next hop.

this will be the easist way to implement kite in NFD.
but it relay on a special Interest. I think your design of implementing PA in LPPacket is a more commom solusion.
the producer could refresh FIB by Interest is a powerful feature, It will change the NDN world.

**Comment by yoursunny** [comment]
If you want to implement KITE in NFD, please make the contribution to https://gerrit.named-data.net .
After your change is accepted by NFD, I'll add what's necessary in NDNts.
