### ISSUE TITLE
`ndn` package Readme is a bit confusing

### ISSUE THREAD

**Issue by JKRhb** [yoursunny/NDNts#25]
For the `@ndn/ndn` package, I think it would be great if it could provide some general guidance and maybe a simple example of how to get started. Although quite funny, especially the "Online demo" that is being linked is a bit confusing, as you expect something NDN-related to happen instead of just seeing the 🤌 emoji. Also considering that the implementation is distributed over a lot of packages, I think it would be nice to make it a bit easier for new users to get started (especially if they encounter NDNts by just searching for "NDN" on npm).

**Comment by yoursunny** [comment]
:pinched_fingers: distills the essence of NDN into a single emoji.
Thus, the `ndn` package works as intended.

I inquired @Pesa and @pulsejet about the history of this emoji and its association with NDN.
I'm told that it's invented by @schneiderklaus, the designer of the congestion control algorithm currently in `@ndn/segmented-object` package.

**Comment by JKRhb** [comment]
> 🤌 distills the essence of NDN into a single emoji.
> Thus, the ndn package works as intended.

Wouldn't it make more sense, though, if the `ndn` package would re-export the main packages that are required to create a working NDN setup? That would make it much easier for people to try out and adopt NDN in their own applications.
